import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Footer from "./Common/Footer";
import NavBar from "./Common/NavBar";
import Home from "./HomePage/Home";

export default function App() {
  return (
    <div>
      <Head>
        <title>Vade Labs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main>
        <Home />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
}
